
-- Telegram → website user linking
create table public.telegram_users (
  chat_id bigint primary key,
  user_id uuid not null,
  username text,
  first_name text,
  linked_at timestamptz not null default now()
);

alter table public.telegram_users enable row level security;

create policy "users see own telegram link"
  on public.telegram_users for select
  to authenticated
  using (user_id = auth.uid() or has_role(auth.uid(), 'admin'));

create policy "admins manage telegram users"
  on public.telegram_users for all
  to authenticated
  using (has_role(auth.uid(), 'admin'))
  with check (has_role(auth.uid(), 'admin'));

-- Temporary link tokens generated by the bot
create table public.telegram_link_tokens (
  token text primary key,
  chat_id bigint not null,
  username text,
  first_name text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '15 minutes'),
  used boolean not null default false
);

alter table public.telegram_link_tokens enable row level security;

create policy "admins manage link tokens"
  on public.telegram_link_tokens for all
  to authenticated
  using (has_role(auth.uid(), 'admin'))
  with check (has_role(auth.uid(), 'admin'));

-- Extend state table to track customer purchase flow
alter table public.telegram_admin_state
  add column if not exists awaiting_receipt_offer_id uuid,
  add column if not exists awaiting_receipt_payment_method text,
  add column if not exists awaiting_receipt_quantity integer;
